name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Install cosign
        run: |
          curl -sSL https://get.sigstore.dev/cosign | sh
          cosign version
      - name: Load cosign private key
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" || cosign import-key-pair --password ${COSIGN_PASSWORD} -private-key -
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

